// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfT9wOvJzu3u9HuLDWU7EU8pm9wogLp4',
    appId: '1:857654207887:web:5ac4922aa0d1ae67bd17fa',
    messagingSenderId: '857654207887',
    projectId: 'stock-analysis-623ae',
    authDomain: 'stock-analysis-623ae.firebaseapp.com',
    storageBucket: 'stock-analysis-623ae.firebasestorage.app',
    measurementId: 'G-YK2QRDP4FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNJAT9FT46n3pid-C8r-jQxpXsinxMi8A',
    appId: '1:857654207887:android:814776a021999f33bd17fa',
    messagingSenderId: '857654207887',
    projectId: 'stock-analysis-623ae',
    storageBucket: 'stock-analysis-623ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0kwOZnAtJerBMKMVxcKc0v2kHtFBlUo',
    appId: '1:857654207887:ios:9e98a59aaf91444ebd17fa',
    messagingSenderId: '857654207887',
    projectId: 'stock-analysis-623ae',
    storageBucket: 'stock-analysis-623ae.firebasestorage.app',
    iosBundleId: 'com.example.stockAnalysisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl0kwOZnAtJerBMKMVxcKc0v2kHtFBlUo',
    appId: '1:857654207887:ios:9e98a59aaf91444ebd17fa',
    messagingSenderId: '857654207887',
    projectId: 'stock-analysis-623ae',
    storageBucket: 'stock-analysis-623ae.firebasestorage.app',
    iosBundleId: 'com.example.stockAnalysisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCfT9wOvJzu3u9HuLDWU7EU8pm9wogLp4',
    appId: '1:857654207887:web:a1ce46c164fbe8a2bd17fa',
    messagingSenderId: '857654207887',
    projectId: 'stock-analysis-623ae',
    authDomain: 'stock-analysis-623ae.firebaseapp.com',
    storageBucket: 'stock-analysis-623ae.firebasestorage.app',
    measurementId: 'G-VESD5E4JT5',
  );

}